# Introduction {#intro}

Welcome to howtohaptic!
This is a living handbook for designers, researchers, and hapticians of all flavours to quickly reference material related to haptic experience design.

This handbook is currently **under development**.
If you have any questions or concerns, please contact the author, [Oliver Schneider](http://oliverschneider.ca).

## What is haptic

Haptic technology is any technology that engages the sense of touch.
It could be vibrations in your smartphone or video game controller (Vibrotactile Technology, \@ref(tech-vibrotactile), or a robot arm that you push against for physiotherapy (force-feedback, \@ref(tech-forcefeedback)).
It could be **...**
 

## Why is haptic important now

Moving from research lab to industry

## How to use this book
The first half (chapters TODO) offer an both a brief introduction to the sense of touch and the technologies 

  - a short handbook for designers, researchers, and hapticians of all kinds
  - designed primarily for random-access
    - you can read the first ~4 chapters as a high-level overview of haptics
    - you can also just access the chapters that are most important for you
  - introductory overview of haptics with a focus on how to design compelling systems
  - reference guide for some of the most common questions when designing a haptic system
  
## Outline of chapters

1. **Introduction** tells you how to use this book
2. **Why Haptic?** (Chapter \@ref(whyhaptic)) tells you what the value of haptics is - why is it important to know how to design for it
3. **What is Haptic Sense?** (Chapter \@ref(sense)) gives a brief overview of the sense of touch, with links to references
4. **What is Haptic Tech?** (Chapter \@ref(tech)) gives a brief overview of the wide array of haptic technologies, organized into the common groupings
5. **How to Haptic** (Chapter \@ref(howhaptic))gives a primer on designing for haptic senses and technologies.
6. **How to Multisensory** (Chapter \@ref(multisensory)) expands the discussion to multisensory design - how to work with vision, audio, and olfactory feedback.
7. **Example Case Studies** (Chapter \@ref(casestudies)) gives a few detailed examples of haptic experience design, the decisions that hapticians made, and the outcome, to walk readers through the process.
8. **Common Applications** (Chapter \@ref(applications)) lists several common goals and application areas of haptics, with their current status and references to essential literature.

